"""The only git writer in the harness: branches, worktrees, commits, merges, pushes, with refusals in code."""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import tempfile
from typing import Dict, List, Optional, Sequence

BRANCH_NAME = re.compile(r"^(feat|fix|chore|docs|test|refactor|perf|build|ci)/[a-z0-9][a-z0-9-]*$")
BANNED_TRAILER = re.compile(r"co-authored-by\s*:|generated with|generated by|\U0001F916", re.I)
CONFLICT_MARKERS = ("<<<<<<< ", "=======", ">>>>>>> ")


class GitRefused(RuntimeError):
    """A git operation the harness refuses to perform, with the reason a human can act on."""


class GitError(RuntimeError):
    """git itself exited non-zero."""


def worker_env(base: Optional[Dict[str, str]] = None) -> Dict[str, str]:
    """An environment with no push credential: no GitHub token, no credential helper, no gh auth, no SSH identity."""
    env = dict(base if base is not None else os.environ)
    for key in ("GH_TOKEN", "GITHUB_TOKEN", "GH_ENTERPRISE_TOKEN", "GIT_ASKPASS", "SSH_AUTH_SOCK"):
        env.pop(key, None)
    env["GIT_TERMINAL_PROMPT"] = "0"
    env["GIT_CONFIG_COUNT"] = "1"
    env["GIT_CONFIG_KEY_0"] = "credential.helper"
    env["GIT_CONFIG_VALUE_0"] = ""
    env["GIT_SSH_COMMAND"] = "ssh -o BatchMode=yes -o IdentitiesOnly=yes -o IdentityFile=/dev/null"
    env["GH_CONFIG_DIR"] = os.path.join(tempfile.gettempdir(), "komodo-gh-noauth")
    os.makedirs(env["GH_CONFIG_DIR"], exist_ok=True)
    return env


class Git:
    """A repo checkout the orchestrator drives, with every mutation checked against the protected set."""

    def __init__(self, root: str, protected: Sequence[str] = (), remote: str = "origin"):
        self.root = root
        self.protected_patterns = list(protected)
        self.remote = remote

    def run(self, *args: str, cwd: Optional[str] = None, check: bool = True, timeout: int = 120) -> str:
        """Runs git with the given args in the checkout and returns stdout."""
        result = subprocess.run(
            ["git", *args], cwd=cwd or self.root, capture_output=True, text=True, timeout=timeout,
        )
        if check and result.returncode != 0:
            raise GitError("git %s failed: %s" % (" ".join(args), result.stderr.strip() or result.stdout.strip()))
        return result.stdout

    def is_protected(self, branch: str) -> bool:
        """Whether a branch name matches a protected pattern, refs/heads/ prefix stripped."""
        import fnmatch

        name = branch.strip()
        if name.startswith("refs/heads/"):
            name = name[len("refs/heads/"):]
        if name.startswith(self.remote + "/"):
            name = name[len(self.remote) + 1:]
        return any(fnmatch.fnmatchcase(name, pattern) for pattern in self.protected_patterns)

    def current_branch(self, cwd: Optional[str] = None) -> Optional[str]:
        """The checked-out branch, or None when HEAD is detached."""
        result = subprocess.run(["git", "symbolic-ref", "--short", "-q", "HEAD"], cwd=cwd or self.root, capture_output=True, text=True)
        return result.stdout.strip() or None

    def is_clean(self, cwd: Optional[str] = None) -> bool:
        """Whether the working tree has no staged, unstaged, or untracked changes."""
        return not self.run("status", "--porcelain", cwd=cwd).strip()

    def head(self, cwd: Optional[str] = None) -> str:
        """The full HEAD commit hash."""
        return self.run("rev-parse", "HEAD", cwd=cwd).strip()

    def branch_exists(self, name: str) -> bool:
        """Whether a local branch with this name exists."""
        return subprocess.run(["git", "show-ref", "--verify", "--quiet", "refs/heads/" + name], cwd=self.root).returncode == 0

    def default_base(self) -> str:
        """The base branch: the remote HEAD if known, else main, else master."""
        result = subprocess.run(["git", "symbolic-ref", "--short", "-q", "refs/remotes/%s/HEAD" % self.remote], cwd=self.root, capture_output=True, text=True)
        name = result.stdout.strip()
        if name:
            return name.split("/", 1)[1] if name.startswith(self.remote + "/") else name
        for candidate in ("main", "master"):
            if self.branch_exists(candidate):
                return candidate
        raise GitError("cannot determine the base branch; set base in komodo.json")

    def create_branch(self, name: str, start: Optional[str] = None) -> None:
        """Creates and checks out a conventionally named, unprotected branch."""
        if not BRANCH_NAME.match(name):
            raise GitRefused("branch name %r must match <type>/<kebab-case>" % name)
        if self.is_protected(name):
            raise GitRefused("branch name %r is protected" % name)
        if self.branch_exists(name):
            raise GitRefused("branch %r already exists; resume the run or delete the branch" % name)
        args = ["switch", "-c", name]
        if start:
            args.append(start)
        self.run(*args)

    def switch(self, name: str) -> None:
        """Checks out an existing branch."""
        self.run("switch", name)

    def worktree_add(self, path: str, branch: str, start: str) -> None:
        """Creates a worktree on a fresh branch cut from start."""
        if not BRANCH_NAME.match(branch):
            raise GitRefused("worktree branch %r must match <type>/<kebab-case>" % branch)
        if self.is_protected(branch):
            raise GitRefused("worktree branch %r is protected" % branch)
        self.run("worktree", "add", "-b", branch, path, start)

    def worktree_remove(self, path: str, branch: Optional[str] = None) -> None:
        """Removes a worktree the harness created, and its branch when named."""
        if os.path.isdir(path):
            self.run("worktree", "remove", "--force", path, check=False)
            shutil.rmtree(path, ignore_errors=True)
        self.run("worktree", "prune", check=False)
        if branch and self.branch_exists(branch) and not self.is_protected(branch):
            self.run("branch", "-D", branch, check=False)

    def worktrees(self) -> List[str]:
        """Paths of every worktree except the main checkout."""
        out = self.run("worktree", "list", "--porcelain")
        paths = [line[len("worktree "):] for line in out.splitlines() if line.startswith("worktree ")]
        root = os.path.realpath(self.root)
        return [path for path in paths if os.path.realpath(path) != root]

    def commit(self, message: str, cwd: Optional[str] = None, paths: Optional[Sequence[str]] = None) -> Optional[str]:
        """Stages paths (or everything) and commits; refuses trailers and protected branches; returns the hash or None when nothing changed."""
        if BANNED_TRAILER.search(message):
            raise GitRefused("commit message carries a co-author or generated-by trailer")
        branch = self.current_branch(cwd)
        if branch is None:
            raise GitRefused("HEAD is detached; refusing to commit")
        if self.is_protected(branch):
            raise GitRefused("refusing to commit on protected branch %r" % branch)
        if paths:
            self.run("add", "--", *paths, cwd=cwd)
        else:
            self.run("add", "-A", cwd=cwd)
        if not self.run("diff", "--cached", "--name-only", cwd=cwd).strip():
            return None
        self.run("commit", "-q", "-m", message, cwd=cwd)
        return self.head(cwd)

    def merge(self, branch: str, cwd: Optional[str] = None, message: Optional[str] = None) -> bool:
        """Merges branch into the current branch; returns False when conflicts were left for resolution."""
        current = self.current_branch(cwd)
        if current is None or self.is_protected(current):
            raise GitRefused("refusing to merge into %r" % current)
        args = ["merge", "--no-edit", "--no-ff" if message else "--ff"]
        if message:
            args += ["-m", message]
        args.append(branch)
        result = subprocess.run(["git", *args], cwd=cwd or self.root, capture_output=True, text=True)
        if result.returncode == 0:
            return True
        if "CONFLICT" in result.stdout or "CONFLICT" in result.stderr:
            return False
        raise GitError("git merge %s failed: %s" % (branch, result.stderr.strip() or result.stdout.strip()))

    def merge_abort(self, cwd: Optional[str] = None) -> None:
        """Abandons an in-progress merge."""
        self.run("merge", "--abort", cwd=cwd, check=False)

    def conflicted_files(self, cwd: Optional[str] = None) -> List[str]:
        """Paths still carrying unresolved conflicts."""
        out = self.run("diff", "--name-only", "--diff-filter=U", cwd=cwd)
        return [line for line in out.splitlines() if line]

    def files_with_markers(self, paths: Sequence[str], cwd: Optional[str] = None) -> List[str]:
        """Which of paths still contain conflict markers."""
        found = []
        for relative in paths:
            full = os.path.join(cwd or self.root, relative)
            try:
                with open(full, encoding="utf-8", errors="ignore") as handle:
                    text = handle.read()
            except OSError:
                continue
            if any(line.startswith(CONFLICT_MARKERS) for line in text.splitlines()):
                found.append(relative)
        return found

    def has_remote(self) -> bool:
        """Whether the configured remote exists."""
        return subprocess.run(["git", "remote", "get-url", self.remote], cwd=self.root, capture_output=True).returncode == 0

    def push(self, branch: str, set_upstream: bool = True) -> None:
        """Pushes one unprotected branch to the remote by explicit name, never forced."""
        if branch.startswith(("+", ":")) or ":" in branch:
            raise GitRefused("refusing refspec %r; push a plain branch name" % branch)
        if self.is_protected(branch):
            raise GitRefused("refusing to push protected branch %r" % branch)
        args = ["push"]
        if set_upstream:
            args.append("-u")
        args += [self.remote, branch]
        self.run(*args, timeout=300)

    def fetch(self) -> None:
        """Fetches the remote, pruning deleted branches."""
        self.run("fetch", "--prune", self.remote, timeout=300, check=False)

    def diff(self, base: str, cwd: Optional[str] = None, stat: bool = False) -> str:
        """The diff from base to HEAD."""
        args = ["diff", "%s...HEAD" % base]
        if stat:
            args.append("--stat")
        return self.run(*args, cwd=cwd)

    def diff_lines(self, base: str, cwd: Optional[str] = None) -> int:
        """Added plus removed lines from base to HEAD."""
        out = self.run("diff", "--numstat", "%s...HEAD" % base, cwd=cwd)
        total = 0
        for line in out.splitlines():
            parts = line.split("\t")
            if len(parts) >= 2:
                for value in parts[:2]:
                    if value.isdigit():
                        total += int(value)
        return total

    def changed_files(self, base: str, cwd: Optional[str] = None) -> List[str]:
        """Paths changed from base to HEAD."""
        return [line for line in self.run("diff", "--name-only", "%s...HEAD" % base, cwd=cwd).splitlines() if line]

    def log_subjects(self, base: str, cwd: Optional[str] = None) -> List[str]:
        """Commit subjects from base to HEAD, oldest first."""
        out = self.run("log", "--reverse", "--format=%s", "%s..HEAD" % base, cwd=cwd)
        return [line for line in out.splitlines() if line]

    def merged_branches(self, base: str) -> List[str]:
        """Local, unprotected, conventionally named branches already merged into base."""
        out = self.run("branch", "--merged", base, "--format=%(refname:short)")
        return [name for name in out.splitlines() if name and name != base and BRANCH_NAME.match(name) and not self.is_protected(name)]

    def delete_branch(self, name: str) -> None:
        """Deletes a merged local branch; refuses protected names."""
        if self.is_protected(name):
            raise GitRefused("refusing to delete protected branch %r" % name)
        self.run("branch", "-d", name)


def commit_message(kind: str, title: str, bullets: Sequence[str] = ()) -> str:
    """A conventional-commit message with a capped subject and one bullet per change."""
    subject = "%s: %s" % (kind, title.strip().rstrip("."))
    if len(subject) > 72:
        subject = subject[:69].rstrip() + "..."
    body = [("- " + bullet.strip()) for bullet in bullets if bullet.strip()]
    return subject + ("\n\n" + "\n".join(body) if body else "")
