package guard

import (
	"fmt"
	"io"
	"path/filepath"
	"strings"
)

// Case is one row of the table the gate runs: a call, and whether the guard must refuse it.
type Case struct {
	Name    string
	Tool    string
	Input   map[string]any
	Branch  string
	Deny    bool
	Finding string
}

// bash builds a table row for one shell command.
func bash(name, command, branch string, deny bool, finding string) Case {
	return Case{Name: name, Tool: "Bash", Input: map[string]any{"command": command}, Branch: branch, Deny: deny, Finding: finding}
}

// write builds a table row for one file write.
func write(name, path string, deny bool, finding string) Case {
	return Case{Name: name, Tool: "Write", Input: map[string]any{"file_path": path}, Branch: "feat/x", Deny: deny, Finding: finding}
}

// configCases builds one denied row per path the policy protects, so no host is named here.
func configCases(policy Policy) []Case {
	var out []Case
	for _, pattern := range policy.ConfigPaths {
		path := strings.NewReplacer("/**", "/probe", "**/", "", "/*", "/probe").Replace(pattern)
		out = append(out, write("a write under "+pattern, path, true, "host or toolkit config"))
		out = append(out, bash("touching "+pattern, "touch "+path, "feat/x", true, "host or toolkit config"))
	}
	return out
}

// Table is every call the gate checks, half of them allowed.
func Table(policy Policy) []Case {
	return append(configCases(policy), []Case{
		// 1. A critical ref is never committed, pushed, merged, deleted, or forced.
		bash("commit on main", "git commit -m 'feat: thing'", "main", true, "create a branch first"),
		bash("commit on master", "git commit -m 'feat: thing'", "master", true, "create a branch first"),
		bash("push to main by name", "git push origin main", "feat/x", true, "open a pull request"),
		bash("push from main", "git push", "main", true, "open a pull request"),
		bash("force push to main", "git push --force origin main", "feat/x", true, "open a pull request"),
		bash("delete main", "git push --delete origin main", "feat/x", true, "delete main"),
		bash("push HEAD from master", "git push origin HEAD", "master", true, "open a pull request"),
		bash("merge on main", "git merge feat/x", "main", true, "merge button"),
		bash("branch -D main", "git branch -D main", "feat/x", true, "never deleted"),
		bash("branch --delete master", "git branch --delete master", "feat/x", true, "never deleted"),
		bash("update-ref main", "git update-ref refs/heads/main HEAD", "feat/x", true, "never moved by hand"),
		bash("push a refspec onto main", "git push origin feat/x:main", "feat/x", true, "open a pull request"),
		bash("forced refspec onto master", "git push origin +feat/x:master", "feat/x", true, "open a pull request"),
		bash("gh pr merge", "gh pr merge 12 --squash", "feat/x", true, "merge button"),

		// 2. A write never leaves the worktree root.
		write("edit above the root", "../outside/file.go", true, "outside the worktree"),
		write("write an absolute path elsewhere", "/etc/hosts", true, "outside the worktree"),
		bash("rm above the root", "rm ../sibling/file", "feat/x", true, "outside the worktree"),
		bash("mv out of the tree", "mv a.go /tmp/elsewhere.go", "feat/x", true, "outside the worktree"),
		bash("redirect above the root", "echo x > ../outside.txt", "feat/x", true, "outside the worktree"),
		bash("tee above the root", "cat a | tee ../outside.txt", "feat/x", true, "outside the worktree"),

		// A commit message never carries a trailer. The config rows come from the policy itself.
		bash("co-author trailer", "git commit -m 'feat: x\n\nCo-authored-by: A <a@b.c>'", "feat/x", true, "trailer"),
		bash("generated-with trailer", "git commit -m 'feat: x\n\nGenerated with a tool'", "feat/x", true, "trailer"),
		bash("generated-by trailer", "git commit -m 'feat: x\n\nGenerated by a tool'", "feat/x", true, "trailer"),
		bash("robot trailer", "git commit -m 'feat: x\n\n\U0001F916 made this'", "feat/x", true, "trailer"),

		// Inside the worktree an agent is free.
		bash("rm -rf a build directory", "rm -rf node_modules", "feat/x", false, ""),
		bash("reset hard", "git reset --hard HEAD~1", "feat/x", false, ""),
		bash("checkout a file", "git checkout -- internal/line/next.go", "feat/x", false, ""),
		bash("restore a file", "git restore internal/line/next.go", "feat/x", false, ""),
		bash("clean untracked files", "git clean -fd", "feat/x", false, ""),
		bash("force push its own branch", "git push --force origin feat/x", "feat/x", false, ""),
		bash("force push with lease", "git push --force-with-lease", "feat/x", false, ""),
		bash("push and set upstream", "git push -u origin feat/x", "feat/x", false, ""),
		bash("commit on its own branch", "git commit -m 'feat: thing'", "feat/x", false, ""),
		bash("merge main into its branch", "git merge main", "feat/x", false, ""),
		bash("delete its own branch", "git branch -D feat/old", "feat/x", false, ""),
		bash("delete its own remote branch", "git push origin --delete feat/old", "feat/x", false, ""),
		bash("rebase onto main", "git rebase main", "feat/x", false, ""),
		bash("switch to a new branch", "git switch -c feat/y", "feat/x", false, ""),
		bash("amend its own commit", "git commit --amend -m 'feat: thing'", "feat/x", false, ""),
		bash("stash", "git stash push -u -m wip", "feat/x", false, ""),
		bash("tag a release", "git tag -a v2.0.0 -m 'release 2.0.0'", "feat/x", false, ""),
		bash("add a worktree", "git worktree add .komodo/wt/TSK-01.1.1", "feat/x", false, ""),
		bash("remove a source file", "rm internal/line/old.go", "feat/x", false, ""),
		bash("move a source file", "mv internal/line/a.go internal/line/b.go", "feat/x", false, ""),
		bash("copy a source file", "cp internal/line/a.go internal/line/b.go", "feat/x", false, ""),
		bash("redirect into the worktree", "echo x > out.txt", "feat/x", false, ""),
		bash("make a directory", "mkdir -p internal/new", "feat/x", false, ""),
		bash("run the tests", "go test ./...", "feat/x", false, ""),
		bash("run the verify command", "make verify", "feat/x", false, ""),
		bash("install dependencies", "npm install", "feat/x", false, ""),
		bash("open a pull request", "gh pr create --base main --head feat/x --title t --body b", "feat/x", false, ""),
		bash("read a pull request", "gh pr view 12", "feat/x", false, ""),
		bash("commit with a body and no trailer", "git commit -m 'feat: x\n\nWhat it does.'", "feat/x", false, ""),
		bash("sudo is not one of the four denials", "sudo make install", "feat/x", false, ""),
		write("a new source file", "internal/line/new.go", false, ""),
		write("a file in the state directory", ".komodo/results/TSK-01.1.1.json", false, ""),
		write("the repo's own rules", "AGENTS.md", false, ""),
	}...)
}

// RunTable checks every row and returns the rows whose outcome was wrong.
func RunTable(root string, policy Policy) []string {
	var wrong []string
	for _, item := range Table(policy) {
		request := Request{HookEventName: "PreToolUse", ToolName: item.Tool, Cwd: root, ToolInput: item.Input}
		if path, ok := item.Input["file_path"].(string); ok && strings.HasPrefix(path, "~/") {
			request.ToolInput = map[string]any{"file_path": expandHome(path)}
		}
		decision := Check(request, policy, item.Branch)
		switch {
		case decision.Deny != item.Deny:
			verb := "denied"
			if item.Deny {
				verb = "allowed"
			}
			wrong = append(wrong, fmt.Sprintf("%s: %s and should not be", item.Name, verb))
		case item.Deny && item.Finding != "" && !containsAny(decision.Findings, item.Finding):
			wrong = append(wrong, fmt.Sprintf("%s: denied for the wrong reason: %s", item.Name, strings.Join(decision.Findings, "; ")))
		}
	}
	return wrong
}

// Report writes the table's outcome and returns whether every row held.
func Report(root string, policy Policy, out io.Writer) bool {
	table := Table(policy)
	denied := 0
	for _, item := range table {
		if item.Deny {
			denied++
		}
	}
	wrong := RunTable(root, policy)
	for _, line := range wrong {
		fmt.Fprintln(out, line)
	}
	fmt.Fprintf(out, "%d command(s), %d denied, %d allowed, %d wrong\n",
		len(table), denied, len(table)-denied, len(wrong))
	return len(wrong) == 0
}

// expandHome replaces a leading tilde with the user's home directory.
func expandHome(path string) string {
	if !strings.HasPrefix(path, "~/") {
		return path
	}
	home, err := homeDir()
	if err != nil {
		return path
	}
	return filepath.Join(home, path[2:])
}

// containsAny reports whether any finding holds the needle.
func containsAny(findings []string, needle string) bool {
	for _, finding := range findings {
		if strings.Contains(finding, needle) {
			return true
		}
	}
	return false
}
