#!/usr/bin/env python3
"""pre-commit: refuse a protected branch or a trailer, check formatting, lint comments on staged lines."""

from __future__ import annotations

import fnmatch
import os
import re
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(os.path.dirname(HERE)))

TRAILER = re.compile(r"co-authored-by\s*:|generated with|generated by|\U0001F916", re.I)


def git(*args: str) -> str:
    """Runs git in the current repo and returns stdout."""
    return subprocess.run(["git", *args], capture_output=True, text=True).stdout


def load_config(root: str):
    """The repo's komodo config, or defaults when the package is unavailable."""
    try:
        from komodo.config import Config

        return Config.load(root)
    except Exception:
        return None


def protected_patterns(config) -> list:
    """Patterns from config, else the built-in set."""
    if config is not None:
        return config.protected
    return ["main", "master", "trunk", "prod", "production", "release/*", "hotfix/*"]


def staged_files() -> list:
    """Paths staged for this commit, excluding deletions."""
    out = git("diff", "--cached", "--name-only", "--diff-filter=ACMR")
    return [line for line in out.splitlines() if line]


def check_formatting(files: list) -> list:
    """Problems from gofmt on staged Go files; other formatters run inside verify."""
    problems = []
    go_files = [path for path in files if path.endswith(".go")]
    if go_files and shutil.which("gofmt"):
        for path in go_files:
            staged = subprocess.run(["git", "show", ":" + path], capture_output=True, text=True).stdout
            result = subprocess.run(["gofmt", "-l", "/dev/stdin"], input=staged, capture_output=True, text=True)
            if result.stdout.strip():
                problems.append("%s is not gofmt-clean; run gofmt -w %s" % (path, path))
    return problems


def main() -> int:
    """Runs every check and prints every problem before failing."""
    root = git("rev-parse", "--show-toplevel").strip()
    if not root:
        return 0
    os.chdir(root)
    config = load_config(root)
    problems = []

    branch = git("symbolic-ref", "--short", "-q", "HEAD").strip()
    if branch and any(fnmatch.fnmatchcase(branch, pattern) for pattern in protected_patterns(config)):
        problems.append("committing on protected branch %r; create a branch first" % branch)

    message_path = os.environ.get("KOMODO_COMMIT_MSG_FILE") or os.path.join(git("rev-parse", "--git-dir").strip(), "COMMIT_EDITMSG")
    if os.path.isfile(message_path):
        with open(message_path, encoding="utf-8", errors="ignore") as handle:
            if TRAILER.search(handle.read()):
                problems.append("commit message carries a co-author or generated-by trailer")

    files = staged_files()
    problems += check_formatting(files)

    try:
        from komodo import comments

        require = config.get("comments.require", "nonobvious") if config else "nonobvious"
        trivial = int(config.get("comments.trivial_lines", 8)) if config else 8
        findings = comments.check(root, files, staged=True, require=require, trivial_lines=trivial)
        problems += ["%s:%s: %s %s -- %s" % (f["file"], f["line"], f["kind"], f["rule"], f["detail"]) for f in findings]
    except Exception as error:
        sys.stderr.write("pre-commit: comment lint skipped (%s)\n" % error)

    if problems:
        sys.stderr.write("pre-commit: blocked\n")
        for problem in problems:
            sys.stderr.write("  %s\n" % problem)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
