FROM golang:1.26 AS build

COPY komodo-forge-sdk-go /komodo-forge-sdk-go

WORKDIR /app

COPY komodo-<name>-api/go.mod komodo-<name>-api/go.sum ./
RUN go mod download

COPY komodo-<name>-api ./
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /bin/komodo ./...

FROM gcr.io/distroless/base-debian12
COPY --from=build /bin/komodo /komodo
EXPOSE <PORT>
ENTRYPOINT ["/komodo"]
