#!/usr/bin/env python3
"""Cross-compiles the Go hook binary for every supported target and records their checksums, so a committed binary stays provable against its source."""

from __future__ import annotations

import argparse
import hashlib
import os
import shutil
import subprocess
import sys
import tempfile

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE_DIR = os.path.join(REPO_ROOT, "komodo", "hooks", "src")
BIN_DIR = os.path.join(REPO_ROOT, "komodo", "hooks", "bin")
MANIFEST = os.path.join(BIN_DIR, "MANIFEST.sha256")
BINARY = "komodo-hooks"

# Every platform Claude Code ships on, so no machine has to fall back to the Python hooks.
TARGETS = (
    ("darwin", "amd64"),
    ("darwin", "arm64"),
    ("linux", "amd64"),
    ("linux", "arm64"),
    ("windows", "amd64"),
    ("windows", "arm64"),
)

# -buildvcs=false is the critical one: go otherwise stamps the commit hash and dirty flag into the binary.
BUILD_FLAGS = ("-trimpath", "-buildvcs=false", "-ldflags", "-s -w")


def binary_name(goos: str, goarch: str) -> str:
    """The published file name for one target."""
    return "%s-%s-%s%s" % (BINARY, goos, goarch, ".exe" if goos == "windows" else "")


def go_version() -> str:
    """The bare toolchain version such as go1.27.1, without the host platform, or empty when go is absent."""
    if shutil.which("go") is None:
        return ""
    result = subprocess.run(["go", "version"], capture_output=True, text=True)
    parts = result.stdout.split()
    return parts[2] if result.returncode == 0 and len(parts) > 2 else ""


def digest(path: str) -> str:
    """Hex sha256 of a file."""
    sha = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(65536), b""):
            sha.update(chunk)
    return sha.hexdigest()


def compile_target(goos: str, goarch: str, out_dir: str) -> str:
    """Builds one target into out_dir and returns the binary path."""
    out = os.path.join(out_dir, binary_name(goos, goarch))
    # go build leaves an existing output untouched when its embedded build id still matches, so a tampered file would survive.
    if os.path.exists(out):
        os.remove(out)
    env = dict(os.environ, GOOS=goos, GOARCH=goarch, CGO_ENABLED="0")
    result = subprocess.run(["go", "build", *BUILD_FLAGS, "-o", out, "."], cwd=SOURCE_DIR, env=env, capture_output=True, text=True)
    if result.returncode != 0:
        raise SystemExit("build-hooks: %s/%s failed\n%s" % (goos, goarch, result.stderr))
    return out


def write_manifest(entries: dict, version: str) -> None:
    """Writes the checksum manifest that the verify gate reads."""
    lines = ["# generated by scripts/build-hooks.py; do not edit", "# toolchain %s" % version]
    lines += ["%s  %s" % (entries[name], name) for name in sorted(entries)]
    with open(MANIFEST, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")


def read_manifest() -> dict:
    """The recorded name-to-digest pairs, or an empty mapping when no manifest exists."""
    if not os.path.isfile(MANIFEST):
        return {}
    entries = {}
    with open(MANIFEST, encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if line and not line.startswith("#"):
                value, name = line.split(None, 1)
                entries[name.strip()] = value
    return entries


def manifest_version() -> str:
    """The toolchain version recorded in the manifest header, or empty."""
    if not os.path.isfile(MANIFEST):
        return ""
    with open(MANIFEST, encoding="utf-8") as handle:
        for line in handle:
            if line.startswith("# toolchain "):
                return line[len("# toolchain "):].strip()
    return ""


def build() -> int:
    """Cross-compiles every target into the committed bin directory and rewrites the manifest."""
    version = go_version()
    if not version:
        print("build-hooks: go is not on PATH")
        return 1
    os.makedirs(BIN_DIR, exist_ok=True)
    entries = {}
    for goos, goarch in TARGETS:
        path = compile_target(goos, goarch, BIN_DIR)
        name = os.path.basename(path)
        entries[name] = digest(path)
        print("build-hooks: %s  %.1f MB" % (name, os.path.getsize(path) / 1048576))
    write_manifest(entries, version)
    print("build-hooks: wrote %s" % os.path.relpath(MANIFEST, REPO_ROOT))
    return 0


def check() -> int:
    """Verifies committed binaries against the manifest, and against a fresh rebuild when go is available."""
    recorded = read_manifest()
    if not recorded:
        print("check: no manifest; nothing to verify")
        return 0
    problems = []
    for name, expected in sorted(recorded.items()):
        path = os.path.join(BIN_DIR, name)
        if not os.path.isfile(path):
            problems.append("%s is in the manifest but missing from the tree" % name)
        elif digest(path) != expected:
            problems.append("%s does not match its recorded checksum" % name)

    # A different toolchain produces different bytes from identical source, so only an exact match can prove staleness.
    version, recorded_version = go_version(), manifest_version()
    if problems:
        pass
    elif not version:
        print("check: go absent, checksums verified without a rebuild")
    elif version != recorded_version:
        print("check: built with %r, this host has %r; checksums verified without a rebuild" % (recorded_version, version))
    else:
        with tempfile.TemporaryDirectory() as scratch:
            for goos, goarch in TARGETS:
                name = binary_name(goos, goarch)
                if recorded.get(name) != digest(compile_target(goos, goarch, scratch)):
                    problems.append("%s is stale; rerun scripts/build-hooks.py" % name)

    for problem in problems:
        print("check: %s" % problem)
    return 1 if problems else 0


def main() -> int:
    """Builds the binaries, or checks the committed ones when asked."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify committed binaries instead of rebuilding them")
    args = parser.parse_args()
    return check() if args.check else build()


if __name__ == "__main__":
    sys.exit(main())
