#!/usr/bin/env bash

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_FILE="$REPO_DIR/platforms/komodo-bridge/registry.generated.json"

if ! command -v jq >/dev/null 2>&1; then
  echo "gen-bridge-registry: jq is required but not found on PATH." >&2
  exit 1
fi

extract_field() {
  local file="$1" field="$2"
  awk -v f="$field" '
    /^---$/ { c++; next }
    c==1 && $0 ~ "^"f":" {
      sub("^"f":[ ]*", "");
      gsub(/^"|"$/, "");
      print;
      exit
    }
  ' "$file"
}

tmp="$(mktemp)"
echo "[]" >"$tmp"

for dir in "$REPO_DIR"/agents/*/; do
  name="$(basename "$dir")"
  agent_md="${dir}agent.md"
  [ -f "$agent_md" ] || continue

  tier="$(extract_field "$agent_md" tier)"
  duty_class="$(extract_field "$agent_md" duty_class)"
  spawn_only="$(extract_field "$agent_md" spawn_only)"
  [ -z "$spawn_only" ] && spawn_only="false"

  backend="local"
  if [ "$duty_class" = "oversight" ] || [ "$tier" = "heavy" ]; then
    backend="claude"
  fi

  entry="$(jq -n \
    --arg name "$name" \
    --arg tier "$tier" \
    --arg duty_class "$duty_class" \
    --argjson spawn_only "$spawn_only" \
    --arg backend "$backend" \
    '{name: $name, default_tier: $tier, duty_class: $duty_class, spawn_only: $spawn_only, default_backend: $backend}')"

  next="$(mktemp)"
  jq --argjson e "$entry" '. + [$e]' "$tmp" >"$next"
  mv "$next" "$tmp"
done

jq -n \
  --arg note "generated by scripts/gen-bridge-registry.sh from agents/*/agent.md frontmatter — do not hand-edit, regenerate instead" \
  --slurpfile agents "$tmp" \
  '{note: $note, agents: $agents[0]}' >"$OUT_FILE"

rm -f "$tmp"

count="$(jq '.agents | length' "$OUT_FILE")"
echo "gen-bridge-registry: wrote $OUT_FILE ($count agents)"
