package comments

import (
	"os"
	"strings"
	"testing"
)

// rules returns the rule name of every finding, in order.
func rules(findings []Finding) []string {
	var out []string
	for _, finding := range findings {
		out = append(out, finding.Rule)
	}
	return out
}

func TestResolveFamilyByExtensionAndName(t *testing.T) {
	cases := map[string]string{"a/b.go": familyC, "a/b.py": familyHash, "a/b.sql": familyDash,
		"deploy/Dockerfile": familyHash, "a/b.md": ""}
	for path, want := range cases {
		if got := ResolveFamily(path); got != want {
			t.Errorf("ResolveFamily(%q) = %q, want %q", path, got, want)
		}
	}
}

func TestCommentStartIgnoresMarkersInStrings(t *testing.T) {
	if got := CommentStart(`url := "http://example.com" // real`, familyC); got != 28 {
		t.Fatalf("start = %d", got)
	}
	if got := CommentStart(`url := "http://example.com"`, familyC); got != -1 {
		t.Fatalf("a marker inside a string was read as a comment: %d", got)
	}
}

func TestOverLongCommentIsFlagged(t *testing.T) {
	text := "package a\n\nvar x = 1 // " + strings.Repeat("word ", 25) + "\n"
	got := InvalidComments(text, "a/b.go")
	if len(got) != 1 || got[0].Rule != "OVER_WORDS" {
		t.Fatalf("findings = %+v", got)
	}
}

func TestExternalReferenceAndNarrativeAreFlagged(t *testing.T) {
	text := "package a\n\nvar x = 1 // fixes TSK-01.2.3\nvar y = 2 // we should probably keep this\n"
	got := rules(InvalidComments(text, "a/b.go"))
	if len(got) != 2 || got[0] != "EXTERNAL_REF" || got[1] != "NARRATIVE" {
		t.Fatalf("rules = %v", got)
	}
}

func TestDirectivesAreLeftAlone(t *testing.T) {
	text := "package a\n\n//go:generate mockgen -source=a.go\nvar x = 1 // nolint: everything here would otherwise trip every rule we have\n"
	if got := InvalidComments(text, "a/b.go"); len(got) != 0 {
		t.Fatalf("findings = %+v", got)
	}
}

func TestMalformedMarkerIsFlagged(t *testing.T) {
	text := "package a\n\nvar x = 1 // TODO make this faster\n"
	got := rules(InvalidComments(text, "a/b.go"))
	if len(got) != 1 || got[0] != "MALFORMED_MARKER" {
		t.Fatalf("rules = %v", got)
	}
	shaped := "package a\n\nvar x = 1 // TODO: drop the retry once the API returns a cursor\n"
	if got := InvalidComments(shaped, "a/b.go"); len(got) != 0 {
		t.Fatalf("a well-shaped marker was flagged: %+v", got)
	}
}

func TestOverLongBlockAboveAStatementIsFlagged(t *testing.T) {
	text := "package a\n\nfunc F() {\n\t// one line\n\t// two lines\n\tx := 1\n\t_ = x\n}\n"
	got := rules(InvalidComments(text, "a/b.go"))
	if len(got) != 1 || got[0] != "OVER_LINES" {
		t.Fatalf("rules = %v", got)
	}
}

func TestTwoLinesAboveAFunctionArePermitted(t *testing.T) {
	text := "package a\n\n// F does the thing.\n// It returns nothing.\nfunc F() {\n\tx := 1\n\t_ = x\n}\n"
	if got := InvalidComments(text, "a/b.go"); len(got) != 0 {
		t.Fatalf("findings = %+v", got)
	}
}

func TestStackedBlocksAreFlagged(t *testing.T) {
	text := "package a\n\nvar x = 1\n\n// first block\n\n// second block\nvar y = 2\n"
	if !containsRule(InvalidComments(text, "a/b.go"), "STACKED") {
		t.Fatalf("stacked blocks were not flagged: %+v", InvalidComments(text, "a/b.go"))
	}
}

func TestHeaderCommentsAreExempt(t *testing.T) {
	text := "// Package a is the thing, and this header line is deliberately far longer than the twenty word cap allows for a body comment.\npackage a\n"
	if got := InvalidComments(text, "a/b.go"); len(got) != 0 {
		t.Fatalf("a header comment was linted: %+v", got)
	}
}

func TestUndocumentedExportedFunctionIsFound(t *testing.T) {
	text := "package a\n\nfunc Exported() int {\n\tx := 1\n\treturn x\n}\n"
	got := UndocumentedFunctions(text, "a/b.go", "nonobvious")
	if len(got) != 1 || got[0].Name != "Exported" {
		t.Fatalf("undocumented = %+v", got)
	}
}

func TestDocumentedFunctionIsAccepted(t *testing.T) {
	text := "package a\n\n// Exported returns one.\nfunc Exported() int {\n\tx := 1\n\treturn x\n}\n"
	if got := UndocumentedFunctions(text, "a/b.go", "nonobvious"); len(got) != 0 {
		t.Fatalf("undocumented = %+v", got)
	}
}

func TestPrivateTrivialFunctionOwesNothing(t *testing.T) {
	text := "package a\n\nfunc small() int {\n\treturn 1\n}\n"
	if got := UndocumentedFunctions(text, "a/b.go", "nonobvious"); len(got) != 0 {
		t.Fatalf("a trivial private function was asked for a comment: %+v", got)
	}
}

func TestTestFilesAndGeneratedFilesAreSkipped(t *testing.T) {
	text := "package a\n\nfunc Exported() int {\n\tx := 1\n\treturn x\n}\n"
	if got := UndocumentedFunctions(text, "a/b_test.go", "nonobvious"); len(got) != 0 {
		t.Fatalf("a test file was linted: %+v", got)
	}
	generated := "// Code generated by mockgen. DO NOT EDIT.\n" + text
	if got := UndocumentedFunctions(generated, "a/b.go", "nonobvious"); len(got) != 0 {
		t.Fatalf("a generated file was linted: %+v", got)
	}
}

func TestPythonDocstringCountsAsDocumentation(t *testing.T) {
	text := "def exported():\n    \"\"\"Returns one.\"\"\"\n    x = 1\n    return x\n"
	if got := UndocumentedFunctions(text, "a/b.py", "nonobvious"); len(got) != 0 {
		t.Fatalf("a docstring was not counted: %+v", got)
	}
}

func TestPythonWrappedSignatureDocstringIsAccepted(t *testing.T) {
	text := "def exported(\n    a,\n    b,\n):\n    \"\"\"Returns the sum of a and b.\"\"\"\n    x = a + b\n    return x\n"
	if got := UndocumentedFunctions(text, "a/b.py", "nonobvious"); len(got) != 0 {
		t.Fatalf("a wrapped signature's docstring was not seen: %+v", got)
	}
}

func TestDocCommentAboveARustAttributeIsSeen(t *testing.T) {
	text := "package a\n\n// Rounds a value up to the nearest unit.\n#[must_use]\npub fn exported() -> i32 {\n\tlet x = 1;\n\tx\n}\n"
	if got := UndocumentedFunctions(text, "a/b.rs", "exported"); len(got) != 0 {
		t.Fatalf("a doc comment above a rust attribute was not seen: %+v", got)
	}
}

func TestDocCommentAboveACSharpAttributeIsSeen(t *testing.T) {
	text := "namespace A;\n\n/// <summary>Returns the legacy total.</summary>\n[Obsolete(\"use Total\")]\npublic int Exported() {\n\tvar x = 1;\n\treturn x;\n}\n"
	if got := UndocumentedFunctions(text, "a/b.cs", "Exported"); len(got) != 0 {
		t.Fatalf("a doc comment above a C# attribute was not seen: %+v", got)
	}
}

func TestDocCommentAboveAJavaAnnotationIsSeen(t *testing.T) {
	text := "package a;\n\n// Handles the health check endpoint.\n@GetMapping(\"/health\")\npublic String exported() {\n\tString x = \"ok\";\n\treturn x;\n}\n"
	if got := UndocumentedFunctions(text, "a/b.java", "exported"); len(got) != 0 {
		t.Fatalf("a doc comment above a java annotation was not seen: %+v", got)
	}
}

func TestIOAndIEAreNotFirstPerson(t *testing.T) {
	text := "package a\n\nvar x = 1 // reads the I/O buffer before the next write, i.e. before flush\n"
	if got := InvalidComments(text, "a/b.go"); len(got) != 0 {
		t.Fatalf("I/O or i.e. was read as first person: %+v", got)
	}
}

func TestLonePronounIIsStillFirstPerson(t *testing.T) {
	text := "package a\n\nvar x = 1 // I return the cached value here\n"
	got := rules(InvalidComments(text, "a/b.go"))
	if len(got) != 1 || got[0] != "NARRATIVE" {
		t.Fatalf("rules = %v", got)
	}
}

func TestUsedToAsPurposeIsNotHistory(t *testing.T) {
	text := "package a\n\n// Config holds the region and endpoint used to construct a Client.\ntype Config struct{}\n"
	if got := InvalidComments(text, "a/b.go"); len(got) != 0 {
		t.Fatalf("a purpose phrase was flagged: %+v", got)
	}
}

func TestUsedToAsHistoryIsStillFlagged(t *testing.T) {
	text := "package a\n\nvar x = 1 // This used to call X.\n"
	got := rules(InvalidComments(text, "a/b.go"))
	if len(got) != 1 || got[0] != "NARRATIVE" {
		t.Fatalf("rules = %v", got)
	}
}

func TestGeneratedLockfileIsSkipped(t *testing.T) {
	text := "lockfileVersion: '6.0'\n\ndependencies:\n  foo: 1.2.3 # EPIC-01 pin\n"
	if got := InvalidComments(text, "pnpm-lock.yaml"); len(got) != 0 {
		t.Fatalf("a generated lockfile was flagged: %+v", got)
	}
}

func TestOverLongCharacterCommentIsFlaggedSeparately(t *testing.T) {
	text := "package a\n\nvar x = 1 // " + strings.Repeat("alphabetic ", 15) + "\n"
	got := rules(InvalidComments(text, "a/b.go"))
	if len(got) != 1 || got[0] != "OVER_CHARS" {
		t.Fatalf("rules = %v", got)
	}
}

func TestHashInsideADocstringIsNotAComment(t *testing.T) {
	text := "def exported():\n    \"\"\"Returns one # not a comment at all, and long enough to break every cap the lint has.\"\"\"\n    return 1\n"
	if got := InvalidComments(text, "a/b.py"); len(got) != 0 {
		t.Fatalf("a hash inside a docstring was linted: %+v", got)
	}
}

func TestCheckReportsOneLinePerProblem(t *testing.T) {
	dir := t.TempDir()
	path := dir + "/a.go"
	body := "package a\n\nfunc Exported() int {\n\tx := 1\n\treturn x\n}\n"
	if err := writeFile(path, body); err != nil {
		t.Fatal(err)
	}
	out, err := Check(dir, []string{"a.go"}, "nonobvious")
	if err != nil {
		t.Fatal(err)
	}
	if len(out) != 1 || !strings.Contains(out[0], "UNDOCUMENTED") {
		t.Fatalf("out = %v", out)
	}
}

func TestCheckDiffIgnoresAProblemOutsideTheTouchedLines(t *testing.T) {
	dir := t.TempDir()
	path := dir + "/a.go"
	body := "package a\n\nfunc Old() int {\n\tx := 1\n\treturn x\n}\n\nfunc New() int {\n\ty := 1\n\treturn y\n}\n"
	if err := writeFile(path, body); err != nil {
		t.Fatal(err)
	}

	out, err := CheckDiff(dir, map[string][]int{"a.go": {8}}, "nonobvious")
	if err != nil {
		t.Fatal(err)
	}
	if len(out) != 1 || !strings.Contains(out[0], "New") {
		t.Fatalf("out = %v, want only the touched New finding", out)
	}
}

func TestCheckDiffReportsNothingWhenNoTouchedLineHasAProblem(t *testing.T) {
	dir := t.TempDir()
	path := dir + "/a.go"
	body := "package a\n\nfunc Old() int {\n\tx := 1\n\treturn x\n}\n"
	if err := writeFile(path, body); err != nil {
		t.Fatal(err)
	}

	out, err := CheckDiff(dir, map[string][]int{"a.go": {4}}, "nonobvious")
	if err != nil {
		t.Fatal(err)
	}
	if len(out) != 0 {
		t.Fatalf("out = %v, want none", out)
	}
}

// containsRule reports whether any finding carries the rule.
func containsRule(findings []Finding, rule string) bool {
	for _, finding := range findings {
		if finding.Rule == rule {
			return true
		}
	}
	return false
}

// writeFile writes a test fixture.
func writeFile(path, body string) error { return os.WriteFile(path, []byte(body), 0o644) }

func TestLineCommentAboveATopLevelScriptDeclarationIsFlagged(t *testing.T) {
	for _, decl := range []string{"function at() {", "const LIMIT = 3;", "export class Box {", "interface Shape {", "type Id = string;"} {
		text := "// Walks a path through unknown JSON.\n" + decl + "\n  return 1;\n}\n"
		if got := rules(InvalidComments(text, "a/b.ts")); len(got) != 1 || got[0] != "LINE_DOC" {
			t.Errorf("%q: rules = %v", decl, got)
		}
	}
}

func TestLineCommentInsideAScriptBodyOrAboveAStatementIsPermitted(t *testing.T) {
	text := "/** Sums the list. */\nfunction sum() {\n  // Starts from zero.\n  const total = 0;\n  return total;\n}\n\n// Runs when invoked directly.\nif (main) {\n  sum();\n}\n"
	if got := InvalidComments(text, "a/b.ts"); len(got) != 0 {
		t.Fatalf("findings = %+v", got)
	}
}

func TestLineCommentAboveAGoDeclarationIsPermitted(t *testing.T) {
	text := "package a\n\n// limit caps the retries.\nconst limit = 3\n"
	if got := InvalidComments(text, "a/b.go"); len(got) != 0 {
		t.Fatalf("findings = %+v", got)
	}
}

func TestLeadingScriptDocCommentNeedsAModuleTag(t *testing.T) {
	bare := "/** Builds the contract. */\nimport { a } from 'b';\n"
	if got := rules(InvalidComments(bare, "a/b.ts")); len(got) != 1 || got[0] != "MODULE_TAG" {
		t.Fatalf("rules = %v", got)
	}
	tagged := "/**\n * Builds the contract.\n *\n * @packageDocumentation\n */\nimport { a } from 'b';\n"
	if got := InvalidComments(tagged, "a/b.ts"); len(got) != 0 {
		t.Fatalf("a tagged module comment was flagged: %+v", got)
	}
	declared := "/** Builds the contract. */\nexport function build() {\n  return 1;\n}\n"
	if got := InvalidComments(declared, "a/b.ts"); len(got) != 0 {
		t.Fatalf("a declaration's doc comment was flagged: %+v", got)
	}
}

func TestShellScriptWithoutAHeaderIsFlagged(t *testing.T) {
	bare := "#!/usr/bin/env bash\nset -euo pipefail\necho hi\n"
	if got := rules(InvalidComments(bare, "scripts/a.sh")); len(got) != 1 || got[0] != "SHELL_HEADER" {
		t.Fatalf("rules = %v", got)
	}
	directive := "#!/usr/bin/env bash\n# shellcheck disable=SC2034\nx=1\n"
	if got := rules(InvalidComments(directive, "scripts/a.sh")); len(got) != 1 || got[0] != "SHELL_HEADER" {
		t.Fatalf("a directive passed as a header: %v", got)
	}
	headed := "#!/usr/bin/env bash\n# Prints a greeting.\nset -euo pipefail\necho hi\n"
	if got := InvalidComments(headed, "scripts/a.sh"); len(got) != 0 {
		t.Fatalf("a headed script was flagged: %+v", got)
	}
	if got := InvalidComments("print('hi')\n", "a/b.py"); len(got) != 0 {
		t.Fatalf("a non-shell hash file was flagged: %+v", got)
	}
}

func TestShellFunctionsAreDeclarations(t *testing.T) {
	for line, want := range map[string]string{"deploy() {": "deploy", "function deploy {": "deploy", "  build_all () {": "build_all", "echo hi": ""} {
		if got := FunctionName(line, ".sh"); got != want {
			t.Errorf("FunctionName(%q) = %q, want %q", line, got, want)
		}
	}
	body := strings.Repeat("  echo step\n", 10)
	text := "#!/usr/bin/env bash\n# Deploys.\nset -eu\n\ndeploy() {\n" + body + "}\n"
	if got := UndocumentedFunctions(text, "scripts/a.sh", "nonobvious"); len(got) != 1 || got[0].Name != "deploy" {
		t.Fatalf("undocumented = %+v", got)
	}
}

func TestLineCommentAboveAClassMethodIsFlagged(t *testing.T) {
	text := "export class Box {\n  // Builds the box.\n  build() {\n    return 1;\n  }\n}\n"
	if got := rules(InvalidComments(text, "a/b.ts")); len(got) != 1 || got[0] != "LINE_DOC" {
		t.Fatalf("// above a class method was not flagged: rules = %v", got)
	}
}

func TestLineCommentAboveAnIfInsideAMethodIsPermitted(t *testing.T) {
	text := "export class Box {\n  build() {\n    // Guards the empty case.\n    if (x) {\n      return 1;\n    }\n    return 0;\n  }\n}\n"
	if got := InvalidComments(text, "a/b.ts"); len(got) != 0 {
		t.Fatalf("a comment above an if statement was flagged: %+v", got)
	}
}

func TestBlockDocCommentTakesTheWordCap(t *testing.T) {
	text := "/**\n * Builds the contract from " + strings.Repeat("word ", 22) + "fields.\n */\nexport function build() {\n  return 1;\n}\n"
	got := rules(InvalidComments(text, "a/b.ts"))
	if len(got) != 1 || got[0] != "OVER_WORDS" {
		t.Fatalf("a /** */ comment skipped the word cap: rules = %v", got)
	}
}

func TestBlockDocCommentTakesTheWordingChecks(t *testing.T) {
	text := "/**\n * We previously built this differently.\n */\nexport function build() {\n  return 1;\n}\n"
	got := rules(InvalidComments(text, "a/b.ts"))
	if len(got) != 1 || got[0] != "NARRATIVE" {
		t.Fatalf("a /** */ comment skipped the wording checks: rules = %v", got)
	}
}
