package comments

import (
	"os"
	"strings"
	"testing"
)

// rules returns the rule name of every finding, in order.
func rules(findings []Finding) []string {
	var out []string
	for _, finding := range findings {
		out = append(out, finding.Rule)
	}
	return out
}

func TestResolveFamilyByExtensionAndName(t *testing.T) {
	cases := map[string]string{"a/b.go": familyC, "a/b.py": familyHash, "a/b.sql": familyDash,
		"deploy/Dockerfile": familyHash, "a/b.md": ""}
	for path, want := range cases {
		if got := ResolveFamily(path); got != want {
			t.Errorf("ResolveFamily(%q) = %q, want %q", path, got, want)
		}
	}
}

func TestCommentStartIgnoresMarkersInStrings(t *testing.T) {
	if got := CommentStart(`url := "http://example.com" // real`, familyC); got != 28 {
		t.Fatalf("start = %d", got)
	}
	if got := CommentStart(`url := "http://example.com"`, familyC); got != -1 {
		t.Fatalf("a marker inside a string was read as a comment: %d", got)
	}
}

func TestOverLongCommentIsFlagged(t *testing.T) {
	text := "package a\n\nvar x = 1 // " + strings.Repeat("word ", 25) + "\n"
	got := InvalidComments(text, "a/b.go")
	if len(got) != 1 || got[0].Rule != "OVER_WORDS" {
		t.Fatalf("findings = %+v", got)
	}
}

func TestExternalReferenceAndNarrativeAreFlagged(t *testing.T) {
	text := "package a\n\nvar x = 1 // fixes TSK-01.2.3\nvar y = 2 // we should probably keep this\n"
	got := rules(InvalidComments(text, "a/b.go"))
	if len(got) != 2 || got[0] != "EXTERNAL_REF" || got[1] != "NARRATIVE" {
		t.Fatalf("rules = %v", got)
	}
}

func TestDirectivesAreLeftAlone(t *testing.T) {
	text := "package a\n\n//go:generate mockgen -source=a.go\nvar x = 1 // nolint: everything here would otherwise trip every rule we have\n"
	if got := InvalidComments(text, "a/b.go"); len(got) != 0 {
		t.Fatalf("findings = %+v", got)
	}
}

func TestMalformedMarkerIsFlagged(t *testing.T) {
	text := "package a\n\nvar x = 1 // TODO make this faster\n"
	got := rules(InvalidComments(text, "a/b.go"))
	if len(got) != 1 || got[0] != "MALFORMED_MARKER" {
		t.Fatalf("rules = %v", got)
	}
	shaped := "package a\n\nvar x = 1 // TODO: drop the retry once the API returns a cursor\n"
	if got := InvalidComments(shaped, "a/b.go"); len(got) != 0 {
		t.Fatalf("a well-shaped marker was flagged: %+v", got)
	}
}

func TestOverLongBlockAboveAStatementIsFlagged(t *testing.T) {
	text := "package a\n\nfunc F() {\n\t// one line\n\t// two lines\n\tx := 1\n\t_ = x\n}\n"
	got := rules(InvalidComments(text, "a/b.go"))
	if len(got) != 1 || got[0] != "OVER_LINES" {
		t.Fatalf("rules = %v", got)
	}
}

func TestTwoLinesAboveAFunctionArePermitted(t *testing.T) {
	text := "package a\n\n// F does the thing.\n// It returns nothing.\nfunc F() {\n\tx := 1\n\t_ = x\n}\n"
	if got := InvalidComments(text, "a/b.go"); len(got) != 0 {
		t.Fatalf("findings = %+v", got)
	}
}

func TestStackedBlocksAreFlagged(t *testing.T) {
	text := "package a\n\nvar x = 1\n\n// first block\n\n// second block\nvar y = 2\n"
	if !containsRule(InvalidComments(text, "a/b.go"), "STACKED") {
		t.Fatalf("stacked blocks were not flagged: %+v", InvalidComments(text, "a/b.go"))
	}
}

func TestHeaderCommentsAreExempt(t *testing.T) {
	text := "// Package a is the thing, and this header line is deliberately far longer than the twenty word cap allows for a body comment.\npackage a\n"
	if got := InvalidComments(text, "a/b.go"); len(got) != 0 {
		t.Fatalf("a header comment was linted: %+v", got)
	}
}

func TestUndocumentedExportedFunctionIsFound(t *testing.T) {
	text := "package a\n\nfunc Exported() int {\n\tx := 1\n\treturn x\n}\n"
	got := UndocumentedFunctions(text, "a/b.go", "nonobvious")
	if len(got) != 1 || got[0].Name != "Exported" {
		t.Fatalf("undocumented = %+v", got)
	}
}

func TestDocumentedFunctionIsAccepted(t *testing.T) {
	text := "package a\n\n// Exported returns one.\nfunc Exported() int {\n\tx := 1\n\treturn x\n}\n"
	if got := UndocumentedFunctions(text, "a/b.go", "nonobvious"); len(got) != 0 {
		t.Fatalf("undocumented = %+v", got)
	}
}

func TestPrivateTrivialFunctionOwesNothing(t *testing.T) {
	text := "package a\n\nfunc small() int {\n\treturn 1\n}\n"
	if got := UndocumentedFunctions(text, "a/b.go", "nonobvious"); len(got) != 0 {
		t.Fatalf("a trivial private function was asked for a comment: %+v", got)
	}
}

func TestTestFilesAndGeneratedFilesAreSkipped(t *testing.T) {
	text := "package a\n\nfunc Exported() int {\n\tx := 1\n\treturn x\n}\n"
	if got := UndocumentedFunctions(text, "a/b_test.go", "nonobvious"); len(got) != 0 {
		t.Fatalf("a test file was linted: %+v", got)
	}
	generated := "// Code generated by mockgen. DO NOT EDIT.\n" + text
	if got := UndocumentedFunctions(generated, "a/b.go", "nonobvious"); len(got) != 0 {
		t.Fatalf("a generated file was linted: %+v", got)
	}
}

func TestPythonDocstringCountsAsDocumentation(t *testing.T) {
	text := "def exported():\n    \"\"\"Returns one.\"\"\"\n    x = 1\n    return x\n"
	if got := UndocumentedFunctions(text, "a/b.py", "nonobvious"); len(got) != 0 {
		t.Fatalf("a docstring was not counted: %+v", got)
	}
}

func TestPythonWrappedSignatureDocstringIsAccepted(t *testing.T) {
	text := "def exported(\n    a,\n    b,\n):\n    \"\"\"Returns the sum of a and b.\"\"\"\n    x = a + b\n    return x\n"
	if got := UndocumentedFunctions(text, "a/b.py", "nonobvious"); len(got) != 0 {
		t.Fatalf("a wrapped signature's docstring was not seen: %+v", got)
	}
}

func TestDocCommentAboveARustAttributeIsSeen(t *testing.T) {
	text := "package a\n\n// Rounds a value up to the nearest unit.\n#[must_use]\npub fn exported() -> i32 {\n\tlet x = 1;\n\tx\n}\n"
	if got := UndocumentedFunctions(text, "a/b.rs", "exported"); len(got) != 0 {
		t.Fatalf("a doc comment above a rust attribute was not seen: %+v", got)
	}
}

func TestDocCommentAboveAJavaAnnotationIsSeen(t *testing.T) {
	text := "package a;\n\n// Handles the health check endpoint.\n@GetMapping(\"/health\")\npublic String exported() {\n\tString x = \"ok\";\n\treturn x;\n}\n"
	if got := UndocumentedFunctions(text, "a/b.java", "exported"); len(got) != 0 {
		t.Fatalf("a doc comment above a java annotation was not seen: %+v", got)
	}
}

func TestIOAndIEAreNotFirstPerson(t *testing.T) {
	text := "package a\n\nvar x = 1 // reads the I/O buffer before the next write, i.e. before flush\n"
	if got := InvalidComments(text, "a/b.go"); len(got) != 0 {
		t.Fatalf("I/O or i.e. was read as first person: %+v", got)
	}
}

func TestLonePronounIIsStillFirstPerson(t *testing.T) {
	text := "package a\n\nvar x = 1 // I return the cached value here\n"
	got := rules(InvalidComments(text, "a/b.go"))
	if len(got) != 1 || got[0] != "NARRATIVE" {
		t.Fatalf("rules = %v", got)
	}
}

func TestOverLongCharacterCommentIsFlaggedSeparately(t *testing.T) {
	text := "package a\n\nvar x = 1 // " + strings.Repeat("alphabetic ", 15) + "\n"
	got := rules(InvalidComments(text, "a/b.go"))
	if len(got) != 1 || got[0] != "OVER_CHARS" {
		t.Fatalf("rules = %v", got)
	}
}

func TestHashInsideADocstringIsNotAComment(t *testing.T) {
	text := "def exported():\n    \"\"\"Returns one # not a comment at all, and long enough to break every cap the lint has.\"\"\"\n    return 1\n"
	if got := InvalidComments(text, "a/b.py"); len(got) != 0 {
		t.Fatalf("a hash inside a docstring was linted: %+v", got)
	}
}

func TestCheckReportsOneLinePerProblem(t *testing.T) {
	dir := t.TempDir()
	path := dir + "/a.go"
	body := "package a\n\nfunc Exported() int {\n\tx := 1\n\treturn x\n}\n"
	if err := writeFile(path, body); err != nil {
		t.Fatal(err)
	}
	out, err := Check(dir, []string{"a.go"}, "nonobvious")
	if err != nil {
		t.Fatal(err)
	}
	if len(out) != 1 || !strings.Contains(out[0], "UNDOCUMENTED") {
		t.Fatalf("out = %v", out)
	}
}

// containsRule reports whether any finding carries the rule.
func containsRule(findings []Finding, rule string) bool {
	for _, finding := range findings {
		if finding.Rule == rule {
			return true
		}
	}
	return false
}

// writeFile writes a test fixture.
func writeFile(path, body string) error { return os.WriteFile(path, []byte(body), 0o644) }
